Amend paths

diff --git a/sage-spin b/sage-spin
--- a/sage-spin
+++ b/sage-spin
@@ -1,56 +1,69 @@
 #!/bin/bash
+#
 # This script:
-# - Creates a new directory for a WordPress site in /var/www.
+#
+# - Creates a new directory for a WordPress site in /var/www/html.
 # - Creates a new WordPress test site, with a fresh database.
-# - Downloads, renames and activates the Roots theme.
+# - Downloads, renames and activates the Sage starter theme.
 # - Downloads & activates the "Soil" plugin.
 # - Installs node & bower dependencies by running npm install.
 # - Requires WP-CLI: http://wp-cli.org/
-# Ubuntu: add this script to /usr/local/bin
-# Make it executable, then you can invoke it by typing "wp-spin" in the terminal.
+#
+# Ubuntu: Add this script to `/usr/local/bin`
+# Make it executable: `sudo chmod u+x /usr/local/bin/sage-spin` then you can invoke it by typing "sage-spin" in the terminal
 
 # ------------------------------------------------------------------------------
-# Set repo location
+# Set repo location for starter theme
+#
 sagerepo=git@github.com:roots/sage.git
-#rootsrepo=
-# ------------------------------------------------------------------------------
-# Set up directory, download wp core
 
-echo -e "Please enter the name of the new wp directory:"
+# ------------------------------------------------------------------------------
+# Set up directory
+
+echo -e "Please enter the full path to the new wp directory, e.g. /var/www/html/newproject:"
 read  wp_dir
-cd /var/www
+
+# basename of the $DIR - used as the destination directory, under `/var/www/html`
+DEST_DIR= $(basename $wp_dir)
+
+# ------------------------------------------------------------------------------
+# Create new directory and use WP-CLI to download WordPress
+
+
 mkdir $wp_dir
-sudo chown -R $USER /var/www/$wp_dir
-cd /var/www/$wp_dir
+sudo chown -R $USER $wp_dir
+cd $wp_dir
 wp core download
-echo "The new directory has been created at /var/www/$wp_dir"
+echo "The new directory has been created at $wp_dir"
 echo "It is owned by \"$USER\""
 echo "WordPress core has been downloaded"
 
 # ------------------------------------------------------------------------------
 # Build new database
-echo -e "This script will create a local database with a new user. Username & password based on DB name, but this is OK because we're working LOCALLY."
+# ------------------------------------------------------------------------------
+
+echo -e "This script will create a local database with a new user."
 echo -e "Enter the name of the new database:"
 read  db_name
 
 # Set up variables
-# Username is just the "salted" db name. For publicly accessible databases, make this more secure.
+# Username is just the "salted" db name. For publicly accessible databases,
+# consider making this more secure.
+
 newuser=$db_name
 newuser+=_user
-# Password is just the "salted" db name. Adjust this for better passwords - require user input.
-newpassword=$db_name
-newpassword+=_pass1234
+
+echo -e "Enter a STRONG password for the new database:"
+read newpassword
 
 # For security purposes, ask for a table prefix. Default to 'wp_'
-# Do this on the local dev site to ease later uploads
 dbprefix=wp_
-
 echo -e "Please enter a database table prefix. Leave out the underscore. Defaults to 'wp_'."
 read dbprefix
 dbprefix+="_"
 
 if [ "$dbprefix" = "" ]; then
-    $dbprefix=wp_
+  $dbprefix=wp_
 fi
 
 echo -e "Enter the MySQL root password:"
@@ -59,121 +72,147 @@ read  rootpassword
 db="create database $db_name;GRANT ALL PRIVILEGES ON $db_name.* TO $newuser@localhost IDENTIFIED BY '$newpassword';FLUSH PRIVILEGES;"
 mysql -u root -p$rootpassword -e "$db"
 
-if [ $? != "0" ]; then  # Note: "0" is the return from successful completion of the previous operation in BASH.
- echo "[Error]: Database creation failed"
- exit 1
+if [ $? != "0" ]; then  # NB "0" is the return from successful completion of the previous operation in BASH.
+echo "[Error]: Database creation failed"
+exit 1
 else
 
-# Set up wp-config.php. These are WP-CLI commands.
+# ------------------------------------------------------------------------------
+# Set up wp-config.php using WP-CLI
 # ------------------------------------------------------------------------------
 
 wp core config --dbname=$db_name --dbuser=$newuser --dbpass=$newpassword --dbhost=localhost --dbprefix=$dbprefix
 
-# Install WordPress. Uses WP-CLI.
 # ------------------------------------------------------------------------------
-
-echo -e "Enter a strong password - your database may be exported to a publicly accessible server, so please set a strong password."
+# Install WordPress. WP-CLI.
+# ------------------------------------------------------------------------------
+echo -e "Enter a strong password - your database might be exported to a publicly accessible server, so please set a strong password."
 read strong_password
 
-echo -e "Enter a username. NOT \'ADMIN\'!"
+echo -e "Enter a username. NOT 'ADMIN'!"
 read username
 
-wp core install --url=http://localhost/$wp_dir --title="Basic Test Site" --admin_user=$username --admin_password=$strong_password --admin_email=you@yourweb.com
+wp core install --url=http://localhost/$DEST_DIR --title="Basic Test Site" --admin_user=$username --admin_password=$strong_password --admin_email=info@carawebs.com
 
-
- echo "------------------------------------------"
- echo " WordPress has been installed successfully: http://localhost/$wp_dir "
- echo "------------------------------------------"
- echo " DB Info: "
- echo ""
- echo " DB Name: $dbname"
- echo " DB User: $newuser"
- echo " DB Pass: $newpassword"
- echo "------------------------------------------"
- echo " WordPress User details:"
- echo ""
- echo " WP username: $username"
- echo " WP password: $strong_password"
+echo "------------------------------------------"
+echo " WordPress has been installed successfully: http://localhost/$DEST_DIR "
+echo "------------------------------------------"
+echo " DB Info: "
+echo ""
+echo " DB Name: $dbname"
+echo " DB User: $newuser"
+echo " DB Pass: $newpassword"
+echo "------------------------------------------"
+echo " WordPress User details:"
+echo ""
+echo " WP username: $username"
+echo " WP password: $strong_password"
 fi
 
+# ------------------------------------------------------------------------------
 # Set Up Sage Starter Theme
 # ------------------------------------------------------------------------------
 
+# Use node to amend JSON data in the manifest
+amend_manifest () {
+
+  jsonFile=$wp_dir/wp-content/themes/$themename/assets/manifest.json;
+
+  node > new-${jsonFile} <<EOF
+  //Read data
+  var data = require('./${jsonFile}');
+
+  //Manipulate data
+
+  data.config.devUrl = 'http://localhost/${wp_dir}';
+
+  //Output data
+  console.log(JSON.stringify(data, null, '  '));
+
+EOF
+
+}
+
 setup_theme () {
-cd /var/www/$wp_dir/wp-content/themes
-git clone $sagerepo
-echo -e "Choose a name for the new theme:"
-read themename
-cp -r /var/www/$wp_dir/wp-content/themes/sage /var/www/$wp_dir/wp-content/themes/$themename
 
-# Change first line of style.css to avoid confusion
-themeline="Theme Name: "
-themeline+=$themename
+  cd $wp_dir/wp-content/themes
+  git clone $sagerepo
+  echo -e "Choose a name for the new theme:"
+  read themename
+  cp -r $wp_dir/wp-content/themes/sage $wp_dir/wp-content/themes/$themename
 
-awk -v stylename="$themeline" '{ if (NR == 1) print stylename; else print $0}' /var/www/$wp_dir/wp-content/themes/$themename/style.css > /var/www/$wp_dir/wp-content/themes/$themename/stylemod.css
-sudo cp /var/www/$wp_dir/wp-content/themes/$themename/stylemod.css /var/www/$wp_dir/wp-content/themes/$themename/style.css
-rm -rf /var/www/$wp_dir/wp-content/themes/$themename/stylemod.css
+  # Change first line of style.css to avoid confusion
+  themeline="Theme Name:         "
+  themeline+=$themename
 
-echo -e "-------------------------------------------------------------------------"
-echo -e "The first line of style.css has been amended"
-echo -e "to reflect your theme name - don\'t forget to amend the rest of this file."
-echo -e "NB: this script has appended a line to wp-config.php to set up the Roots development environment."
-echo -e "-------------------------------------------------------------------------"
+  awk -v stylename="$themeline" '{ if (NR == 2) print stylename; else print $0}' $wp_dir/wp-content/themes/$themename/style.css > $wp_dir/wp-content/themes/$themename/stylemod.css
+  sudo cp $wp_dir/wp-content/themes/$themename/stylemod.css $wp_dir/wp-content/themes/$themename/style.css
+  rm -rf $wp_dir/wp-content/themes/$themename/stylemod.css
 
-# Backup original config file
-cp /var/www/$wp_dir/wp-config.php /var/www/$wp_dir/wp-config.bak.php
+  echo -e "-------------------------------------------------------------------------"
+  echo -e "The first line of style.css has been amended"
+  echo -e "to reflect your theme name - don\'t forget to amend the rest of this file."
+  echo -e "NB: this script has appended a line to wp-config.php to set up the Roots development environment."
+  echo -e "-------------------------------------------------------------------------"
 
-# Add a new line
-newline="/* Define the Roots Environment */\ndefine('WP_ENV', 'development');\n"
+  # Backup original config file
+  cp $wp_dir/wp-config.php $wp_dir/wp-config.bak.php
 
-# Insert into a temporary file
-awk -v insert="$newline" 'NR==3{print insert}1' /var/www/$wp_dir/wp-config.php > /var/www/$wp_dir/wp-config-temp.php
+  newline="/* Define the Roots Environment */\ndefine('WP_ENV', 'development');\n"
+  awk -v insert="$newline" 'NR==3{print insert}1' $wp_dir/wp-config.php > $wp_dir/wp-config-temp.php
 
-# Copy to wp-config.php
-cp /var/www/$wp_dir/wp-config-temp.php /var/www/$wp_dir/wp-config.php
+  cp $wp_dir/wp-config-temp.php $wp_dir/wp-config.php
+
+  # amend JSON Manifest
 
 }
 
 install_soil () {
-cd /var/www/$wp_dir/wp-content/plugins
-git clone https://github.com/roots/soil.git
-wp plugin activate soil
+
+  cd $wp_dir/wp-content/plugins
+  git clone https://github.com/roots/soil.git
+  wp plugin activate soil
+
 }
 
 setup_node () {
-cd /var/www/$wp_dir/wp-content/themes/$themename
 
-# Note: npm runs without sudo if node has been installed on your system by the nvm method:
-# https://github.com/creationix/nvm (recommended!)
-# Otherwise, the npm install command should run as sudo, followed by bower install.
-# For this case comment out line 151 & enable line 152)
-# Or move to the theme directory after installation is complete and run sudo npm install followed by bower install
-npm install
-# sudo npm install
-# bower install
-# For sage, overtly call bower
-bower install
+  cd $wp_dir/wp-content/themes/$themename
+
+  # Note: npm runs without sudo if node has been installed on your system by the nvm method:
+  # https://github.com/creationix/nvm (recommended!)
+  # Otherwise, the npm install command should run as sudo, followed by bower install.
+  # For this case comment out line 133 & enable lines 134 & 135)
+  # Or move to the theme directory after installation is complete and run sudo npm install followed by bower install
+  npm install
+  # sudo npm install
+  # bower install
+  # For sage, overtly call bower
+  bower install
 }
 
 run_gulp () {
-cd /var/www/$wp_dir/wp-content/themes/$themename
-gulp watch
+
+  cd $wp_dir/wp-content/themes/$themename
+  gulp watch
+
 }
 
 activate_theme () {
-cd /var/www/$wp_dir/wp-content/themes/$themename
-wp theme activate $themename
+
+  cd $wp_dir/wp-content/themes/$themename
+  wp theme activate $themename
+
 }
 
 setup_repo () {
-cd /var/www/$wp_dir/wp-content/themes/$themename
 
-# remove existing git repo
-sudo rm -rf /var/www/$wp_dir/wp-content/themes/$themename/.git
-git init
+  cd $wp_dir/wp-content/themes/$themename
 
-repo_name=$1
-
+  # remove existing git repo
+  sudo rm -rf $wp_dir/wp-content/themes/$themename/.git
+  git init
+  repo_name=$1
   dir_name=`basename $(pwd)`
   invalid_credentials=0
 
@@ -216,47 +255,47 @@ repo_name=$1
 
 }
 
-	read -p "Do you want to set up the Sage Starter theme? [y/N]" yn
-	case $yn in
-	[Yy]* ) setup_theme;;
-	[Nn]* ) exit ;;
-	* ) echo "Please answer yes or no.";;
-	esac
+read -p "Do you want to set up the Sage Starter theme? [y/N]" yn
+case $yn in
+  [Yy]* ) setup_theme;;
+  [Nn]* ) exit ;;
+  * ) echo "Please answer yes or no.";;
+esac
 
-	read -p "Set up a new GitHub repo for $themename? [y/N]" yn
-	case $yn in
-	[Yy]* ) setup_repo;;
-	[Nn]* ) ;;
-	* ) echo "Please answer yes or no.";;
-	esac
+read -p "Set up a new GitHub repo for $themename? [y/N]" yn
+case $yn in
+  [Yy]* ) setup_repo;;
+  [Nn]* ) ;;
+  * ) echo "Please answer yes or no.";;
+esac
 
-	read -p "Do you want to install and activate the Roots \"Soil\" plugin? [y/N]" yn
-	case $yn in
-	[Yy]* ) install_soil;;
-	[Nn]* ) exit ;;
-	* ) echo "Please answer yes or no.";;
-	esac
+read -p "Do you want to install and activate the Roots \"Soil\" plugin? [y/N]" yn
+case $yn in
+  [Yy]* ) install_soil;;
+  [Nn]* ) exit ;;
+  * ) echo "Please answer yes or no.";;
+esac
 
-	read -p "Do you want to go to the $themename theme and install node dependencies? [y/N]" yn
-	case $yn in
-	[Yy]* ) setup_node;;
-	[Nn]* ) exit ;;
-	* ) echo "Please answer yes or no.";;
-	esac
+read -p "Do you want to go to the $themename theme and install node dependencies? [y/N]" yn
+case $yn in
+  [Yy]* ) setup_node;;
+  [Nn]* ) exit ;;
+  * ) echo "Please answer yes or no.";;
+esac
 
-	read -p "Do you want to activate the $themename theme? [y/N]" yn
-	case $yn in
-	[Yy]* ) activate_theme;;
-	[Nn]* ) exit ;;
-	* ) echo "Please answer yes or no.";;
-	esac
+read -p "Do you want to activate the $themename theme? [y/N]" yn
+case $yn in
+  [Yy]* ) activate_theme;;
+  [Nn]* ) exit ;;
+  * ) echo "Please answer yes or no.";;
+esac
 
-	read -p "Move to the theme directory and run the gulp build task? [y/N]" yn
-	case $yn in
-	[Yy]* ) run_gulp;;
-	[Nn]* ) exit ;;
-	* ) echo "Please answer yes or no.";;
-	esac
+read -p "Move to the theme directory and run the gulp build task? [y/N]" yn
+case $yn in
+  [Yy]* ) run_gulp;;
+  [Nn]* ) exit ;;
+  * ) echo "Please answer yes or no.";;
+esac
 
 sitelocation="Access your new site: http://localhost/"
 sitelocation+=$wp_dir
